### ISSUE TITLE
Laravel 7 Support

### ISSUE THREAD

**Issue by C0kkie** [elbgoods/laravel-trashmail-rule#10]
Hello,

when will you add laravel 7 support?

**Comment by Gummibeer** [comment]
I will start today with L7 updates. All of my packages here and @Astrotomic should be compatible this week.
The ones with open upgrade requests will be priorized.

**Comment by C0kkie** [comment]
Alright :)

**Comment by Gummibeer** [comment]
It's released: https://github.com/elbgoods/laravel-trashmail-rule/releases/tag/0.6.0
