### ISSUE TITLE
Should we try-catch guzzle/http errors?

### ISSUE THREAD

**Issue by Gummibeer** [elbgoods/laravel-trashmail-rule#4]
Because this package can do HTTP requests it's possible that they fail. How should the package handle them?

* no handling, let the exception travel up the stack
* try-catch and return `true` - no trash mail
* try-catch and return `false` - trash mail
* something else?

**Comment by mstaack** [comment]
my thought:
* given the response is cached i would expect a fallback to latest cached version.
* if no valid cache found/available, it should default to false (default fallback could be configurable)
